name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        A bug is when something works differently than it is expected to.
        ## Remember to search before filing a new report
        Please search for this bug in the [issue tracker](https://github.com/PixelGuys/Cubyz/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug), and use a bug report title that
        would have made your bug report turn up in the search results for your search query.
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce and Observed Behavior
      description: Please describe the observed behavior and how to reproduce it. In case of a crash please attach the stack trace shown in the console.
    validations:
      required: true
