const std = @import("std");

const main = @import("main");
const builtin = @import("builtin");
const BinaryWriter = main.utils.BinaryWriter;
const BinaryReader = main.utils.BinaryReader;
const NeverFailingAllocator = main.heap.NeverFailingAllocator;
const ZonElement = main.ZonElement;

const c = @import("c");

var wordlist: ?[2048][]const u8 = null;

fn wordToIndex(word: []const u8) ?u11 {
	if (wordlist == null) return null;
	for (wordlist.?, 0..) |other, i| {
		if (std.mem.eql(u8, word, other)) {
			return @intCast(i);
		}
	}
	return null;
}

pub fn init() void {
	const wordlistString = main.files.cwd().read(main.globalArena, "assets/cubyz/wordlist") catch |err| {
		std.log.err("Got error while reading word list: {s}", .{@errorName(err)});
		return;
	};
	var splitIterator = std.mem.splitScalar(u8, wordlistString, '\n');
	wordlist = @splat(&.{});
	var i: usize = 0;
	while (splitIterator.next()) |word| {
		wordlist.?[i] = std.mem.trim(u8, word, &std.ascii.whitespace);
		i += 1;
	}
}

pub const KeyTypeEnum = enum(u8) {
	ed25519 = 0,
	ecdsaP256Sha256 = 1,
	mldsa44 = 2,

	pub fn getAlgorithmType(self: KeyTypeEnum) type {
		return switch (self) {
			.ed25519 => std.crypto.sign.Ed25519,
			.ecdsaP256Sha256 => std.crypto.sign.ecdsa.EcdsaP256Sha256,
			.mldsa44 => std.crypto.sign.mldsa.MLDSA44,
		};
	}
};

pub const KeyCollection = struct { // Provides multiple methods to allow server hosts to react when one of the methods is compromised
	const Storage = struct {
		pub var ed25519: std.crypto.sign.Ed25519.KeyPair = undefined;
		pub var ecdsaP256Sha256: std.crypto.sign.ecdsa.EcdsaP256Sha256.KeyPair = undefined;
		pub var mldsa44: std.crypto.sign.mldsa.MLDSA44.KeyPair = undefined;
	};

	pub var initialized: bool = false;

	pub fn init(accountCode: AccountCode) void {
		// These are used to salt the the account code (or seed phrase) for each of the keys so we get unrelated keys in case one of them gets compromised.
		// They were generated by the keyboard mashing RNG
		const keySalts = [_][]const u8{
			"n59zw0qz53q05b73q9a50vmso",
			"4t7z3592a09p85z4piotfh7z",
			"u89564epogz1qi9up5zc94309",
		};
		inline for (comptime std.meta.declarations(Storage), 0..) |decl, i| {
			const hashableString = std.mem.concat(main.stackAllocator.allocator, u8, &.{accountCode.text, keySalts[i]}) catch unreachable;
			defer main.stackAllocator.free(hashableString);
			defer @memset(hashableString, 0);

			var hashedResult: [64]u8 = undefined;

			for (0..2048) |j| {
				const input = if (j == 0) hashableString else &hashedResult;
				var out: [64]u8 = undefined;
				std.crypto.hash.sha2.Sha512.hash(input, &out, .{});
				hashedResult = out;
			}

			const functionType = @TypeOf(@TypeOf(@field(Storage, decl.name)).generateDeterministic);
			const seed = hashedResult[0..@sizeOf(@typeInfo(functionType).@"fn".params[0].type.?)].*;

			@field(Storage, decl.name) = @TypeOf(@field(Storage, decl.name)).generateDeterministic(seed) catch @panic("Failed to generate key pair for " ++ decl.name);
		}
		initialized = true;
	}

	pub fn getPublicKeys(allocator: NeverFailingAllocator) ZonElement {
		std.debug.assert(initialized);
		const result = ZonElement.initObject(allocator);
		inline for (comptime std.meta.declarations(Storage)) |decl| {
			const bytes = blk: {
				if (@hasDecl(@TypeOf(@field(Storage, decl.name).public_key), "toBytes")) {
					break :blk @field(Storage, decl.name).public_key.toBytes();
				} else {
					break :blk @field(Storage, decl.name).public_key.toUncompressedSec1();
				}
			};
			var base64: [std.base64.standard.Encoder.calcSize(bytes.len)]u8 = undefined;
			result.putOwnedString(decl.name, std.base64.standard.Encoder.encode(&base64, &bytes));
		}
		return result;
	}

	pub fn getPublicKey(allocator: NeverFailingAllocator, keyType: KeyTypeEnum) []const u8 {
		std.debug.assert(initialized);
		switch (keyType) {
			inline else => |_typ| {
				const bytes = blk: {
					if (@hasDecl(@TypeOf(@field(Storage, @tagName(_typ)).public_key), "toBytes")) {
						break :blk @field(Storage, @tagName(_typ)).public_key.toBytes();
					} else {
						break :blk @field(Storage, @tagName(_typ)).public_key.toUncompressedSec1();
					}
				};
				var base64: [std.base64.standard.Encoder.calcSize(bytes.len)]u8 = undefined;
				const key = std.base64.standard.Encoder.encode(&base64, &bytes);
				return std.mem.concat(allocator.allocator, u8, &.{@tagName(_typ), ":", key}) catch unreachable;
			},
		}
	}

	pub fn sign(writer: *BinaryWriter, typ: KeyTypeEnum, message: []const u8) void {
		std.debug.assert(initialized);
		switch (typ) {
			inline else => |_typ| {
				const AlgorithmType = _typ.getAlgorithmType();
				var randomBytes: [AlgorithmType.noise_length]u8 = undefined;
				main.io.random(&randomBytes);
				const signature = @field(Storage, @tagName(_typ)).sign(message, randomBytes) catch |err| {
					std.debug.panic("Failed to sign message with error {s}. Maybe try reconnecting, if the error persists, I'd suggest creating a new account", .{@errorName(err)});
				};
				writer.writeSlice(&signature.toBytes());
			},
		}
	}
};

pub const PublicKey = union(KeyTypeEnum) {
	ed25519: std.crypto.sign.Ed25519.PublicKey,
	ecdsaP256Sha256: std.crypto.sign.ecdsa.EcdsaP256Sha256.PublicKey,
	mldsa44: std.crypto.sign.mldsa.MLDSA44.PublicKey,

	pub fn initFromBase64(base64: []const u8, typ: KeyTypeEnum) !PublicKey {
		switch (typ) {
			inline else => |_typ| {
				const KeyType = @TypeOf(@field(KeyCollection.Storage, @tagName(_typ)).public_key);
				const length = if (@hasDecl(KeyType, "fromBytes")) KeyType.encoded_length else KeyType.uncompressed_sec1_encoded_length;
				var bytes: [length]u8 = undefined;
				try std.base64.standard.Decoder.decode(&bytes, base64);
				if (@hasDecl(KeyType, "fromBytes")) {
					return @unionInit(PublicKey, @tagName(_typ), try KeyType.fromBytes(bytes));
				} else {
					return @unionInit(PublicKey, @tagName(_typ), try KeyType.fromSec1(&bytes));
				}
			},
		}
	}

	pub fn verifySignature(self: PublicKey, reader: *BinaryReader, message: []const u8) !void {
		switch (@as(KeyTypeEnum, self)) {
			inline else => |tag| {
				const AlgorithmType = tag.getAlgorithmType();
				const signature: error{InvalidEncoding}!AlgorithmType.Signature = AlgorithmType.Signature.fromBytes((try reader.readSlice(AlgorithmType.Signature.encoded_length))[0..AlgorithmType.Signature.encoded_length].*);
				try (try signature).verify(message, @field(self, @tagName(tag)));
			},
		}
	}
};

/// Also known as a seed phrase, implementation is based on BIP39 with some minor changes and limited to one word list
pub const AccountCode = struct {
	text: []u8,

	fn printInvalidCharError(failureText: *main.ListManaged(u8), codepoint: u21) void {
		failureText.print("Account Code contains invalid character '{u}' (U+{X}), only ASCII letters and whitespaces are allowed.\n", .{codepoint, codepoint});
	}

	pub fn initFromUserInput(text: []const u8, failureText: *main.ListManaged(u8)) AccountCode {
		var result: main.List(u8) = .initCapacity(main.stackAllocator, text.len);
		defer result.deinit(main.stackAllocator);
		defer std.crypto.secureZero(u8, result.items);

		const trimmed = std.mem.trim(u8, text, &std.ascii.whitespace);
		var unicodeIterator = std.unicode.Utf8View.initUnchecked(trimmed).iterator();

		while (unicodeIterator.nextCodepoint()) |codepoint| {
			if (codepoint > 0x7F) {
				printInvalidCharError(failureText, codepoint);
				continue;
			}
			const char: u8 = @intCast(codepoint);
			if (std.ascii.isAlphabetic(char)) {
				result.appendAssumeCapacity(std.ascii.toLower(char));
			} else if (std.ascii.isWhitespace(char)) {
				if (result.items[result.items.len - 1] != ' ') {
					result.appendAssumeCapacity(' ');
				}
			} else {
				printInvalidCharError(failureText, codepoint);
			}
		}
		if (result.items.len == 0) {
			failureText.print("Account Code is empty.\n", .{});
			return .{.text = ""};
		}
		if (result.items[result.items.len - 1] == ' ') _ = result.pop();

		var split = std.mem.splitScalar(u8, result.items, ' ');
		var wordCount: usize = 0;
		var bits: [21]u8 = @splat(0);
		defer std.crypto.secureZero(u8, &bits);
		var failedWordlist: bool = false;
		while (split.next()) |word| {
			wordCount += 1;
			if (wordToIndex(word)) |wordIndex| {
				if (wordCount <= 15) {
					const bitIndex = (wordCount - 1)*11;
					const byteIndex = bitIndex/8;
					const containingRegion: usize = @as(usize, wordIndex) << @intCast(8*3 - 11 - bitIndex%8);

					bits[byteIndex] |= @truncate(containingRegion >> 16);
					bits[byteIndex + 1] |= @truncate(containingRegion >> 8);
					if (byteIndex + 2 < bits.len) bits[byteIndex + 2] |= @truncate(containingRegion);
				}
			} else {
				failureText.print("The {}{s} word of the Account Code is not a part of the wordlist.\n", .{wordCount, if (wordCount == 1) "st" else if (wordCount == 2) "nd" else if (wordCount == 3) "rd" else "th"});
				failedWordlist = true;
			}
		}

		if (wordCount != 15) {
			failureText.print("The Account Code contains an invalid number of words. Should be 15.\n", .{});
			failedWordlist = true;
		}

		if (!failedWordlist) {
			var sha256Result: [32]u8 = undefined;
			defer std.crypto.secureZero(u8, &sha256Result);
			std.crypto.hash.sha2.Sha256.hash(bits[0..20], &sha256Result, .{});
			if (sha256Result[0] >> 3 != bits[20] >> 3) {
				failureText.print("The Account Code has an incorrect checksum.\n", .{});
			}
		}

		return .{
			.text = main.globalAllocator.dupe(u8, result.items),
		};
	}

	pub fn initRandomly() AccountCode {
		if (wordlist == null) @panic("Cannot generate new Account without a valid wordlist.");
		var bits: [21]u8 = undefined;
		defer std.crypto.secureZero(u8, &bits);
		main.io.random(bits[0..20]);
		var sha256Result: [32]u8 = undefined;
		defer std.crypto.secureZero(u8, &sha256Result);
		std.crypto.hash.sha2.Sha256.hash(bits[0..20], &sha256Result, .{});
		bits[20] = sha256Result[0];

		var result: main.List(u8) = .empty;
		defer result.deinit(main.stackAllocator);
		defer std.crypto.secureZero(u8, result.items);

		for (0..15) |i| {
			const bitIndex = i*11;
			const byteIndex = bitIndex/8;

			const containingRegion = @as(usize, bits[byteIndex]) << 16 | @as(usize, bits[byteIndex + 1]) << 8 | if (byteIndex + 2 < bits.len) bits[byteIndex + 2] else 0;
			const wordIndex: u11 = @truncate(containingRegion >> @intCast(8*3 - 11 - bitIndex%8));

			if (i != 0) result.append(main.stackAllocator, ' ');
			result.appendSlice(main.stackAllocator, wordlist.?[wordIndex]);
		}

		return .{
			.text = main.globalAllocator.dupe(u8, result.items),
		};
	}

	pub fn deinit(self: AccountCode) void {
		std.crypto.secureZero(u8, self.text);
		main.globalAllocator.free(self.text);
	}
};

pub const protection = struct {
	const Impl = switch (builtin.os.tag) {
		.windows => WindowsImpl,
		else => NoImpl,
	};

	pub inline fn canProtect() bool {
		return Impl.canProtect;
	}

	pub fn protect(allocator: NeverFailingAllocator, data: []u8) error{ syserr, Unsupported }![]u8 {
		return Impl.protect(allocator, data);
	}

	pub fn unprotect(allocator: NeverFailingAllocator, data: []u8) error{ syserr, Invalid }![]u8 {
		return Impl.unprotect(allocator, data);
	}

	const NoImpl = struct {
		const canProtect = false;

		fn protect(_: NeverFailingAllocator, _: []u8) error{ syserr, Unsupported }![]u8 {
			return error.Unsupported;
		}

		fn unprotect(_: NeverFailingAllocator, _: []u8) error{ syserr, Invalid }![]u8 {
			return error.Invalid;
		}
	};

	const WindowsImpl = struct {
		const canProtect = true;

		fn protect(allocator: NeverFailingAllocator, data: []u8) error{ syserr, Unsupported }![]u8 {
			var plainblob: c.DATA_BLOB = undefined;
			var cipherblob: c.DATA_BLOB = undefined;
			plainblob.cbData = @intCast(data.len);
			plainblob.pbData = @as([*c]u8, data.ptr);
			if (c.CryptProtectData(&plainblob, @as([*c]const c_ushort, null), @as([*c]c.DATA_BLOB, null), null, @as([*c]c.CRYPTPROTECT_PROMPTSTRUCT, null), @as(c_ulong, 0), &cipherblob) == 0) {
				std.log.err("CryptProtectData syscall failed. Errorcode: {}. This should never happen. Please report it to the maintainers.", .{c.GetLastError()});
				return error.syserr;
			}
			defer if (c.LocalFree(cipherblob.pbData) != null) std.log.err("LocalFree syscall failed to free previously allocated memory. Errorcode: {}. This should never happen. Please report it to the maintainers.", .{c.GetLastError()});
			const out: []u8 = allocator.alloc(u8, @intCast(cipherblob.cbData));
			@memcpy(out, cipherblob.pbData);
			return out;
		}

		fn unprotect(allocator: NeverFailingAllocator, data: []u8) error{ syserr, Invalid }![]u8 {
			var plainblob: c.DATA_BLOB = undefined;
			var cipherblob: c.DATA_BLOB = undefined;
			cipherblob.cbData = @intCast(data.len);
			cipherblob.pbData = @as([*c]u8, data.ptr);
			if (c.CryptUnprotectData(&cipherblob, @as([*c][*c]c_ushort, null), @as([*c]c.DATA_BLOB, null), null, @as([*c]c.CRYPTPROTECT_PROMPTSTRUCT, null), @as(c_ulong, 0), &plainblob) == 0) {
				const err = c.GetLastError();
				switch (err) {
					c.ERROR_INVALID_DATA, c.ERROR_INVALID_PARAMETER => return error.Invalid,
					else => {
						std.log.err("CryptUnprotectData syscall failed. Errorcode: {}", .{err});
						return error.syserr;
					},
				}
			}
			var pbDataSlice: []u8 = undefined;
			pbDataSlice.len = plainblob.cbData;
			pbDataSlice.ptr = plainblob.pbData;
			defer {
				std.crypto.secureZero(u8, pbDataSlice);
				if (c.LocalFree(plainblob.pbData) != null) std.log.err("LocalFree syscall failed to free previously allocated memory. Errorcode: {}. This should never happen. Please report it to the maintainers.", .{c.GetLastError()});
			}
			const out: []u8 = allocator.alloc(u8, @intCast(plainblob.cbData));
			@memcpy(out, plainblob.pbData);
			return out;
		}
	};

	test "slice==unprotect(protect(slice))" {
		const slice: []u8 = @as([]u8, @constCast("Test"));
		if (canProtect()) {
			const protected = try protect(main.stackAllocator, slice);
			defer main.stackAllocator.free(protected);
			const unprotected = try unprotect(main.stackAllocator, protected);
			defer main.stackAllocator.free(unprotected);
			try std.testing.expectEqualSlices(u8, slice, unprotected);
		} else {
			return error.SkipZigTest;
		}
	}

	test "Protect fails on unsupported platforms" {
		const slice: []u8 = @as([]u8, @constCast("Test"));
		if (!canProtect()) {
			try std.testing.expectError(error.Unsupported, protect(main.stackAllocator, slice));
			try std.testing.expectError(error.Invalid, unprotect(main.stackAllocator, slice));
		} else {
			return error.SkipZigTest;
		}
	}

	test "Unprotect fails when supplied with garbage" {
		if (canProtect()) {
			const slices: [5][]u8 = .{@as([]u8, @constCast("TestdwadadÖOUWHdöouHIOSUdhöoUHNWLJDKNOÖPAHUIwdoöJKNSdlkjöwuHOÖIhso8zpo9IKj")), @as([]u8, @constCast("Test")), @as([]u8, @constCast("Testd")), @as([]u8, @constCast("")), @as([]u8, @constCast("WIJDp8iU)(du098UÜ=JHd0ü8hz=Ü(HJ0isidjowi8h=(Z\"ß08IJUISdhd0w98hdoi8uoIWUJDoikjsoIKHJOwiuhdOISHNdo9i8H(UIHNASUJhdnbiuJBWGiudjhbIAKUJHnbsiudjkhiWUAHNIUDshjliuAHELIUHFILUHNIUJBDIUHwiuHushoujhdiiuwhIUHsouhdUHwiuhdUAHLsuidhlHU)"))};
			for (slices) |slice| {
				try std.testing.expectError(error.Invalid, unprotect(main.stackAllocator, slice));
			}
		} else {
			return error.SkipZigTest;
		}
	}
};

pub const EncodingType = enum { none, argon2_aes_gcm };

pub const PasswordEncodedAccountCode = struct {
	typ: EncodingType,
	protected: bool,
	salt: []u8,
	nonce: []u8,
	data: []u8,
	authenticationTag: []u8,

	pub const empty: PasswordEncodedAccountCode = .{.typ = .none, .protected = false, .salt = &.{}, .nonce = &.{}, .data = &.{}, .authenticationTag = &.{}};

	pub fn initFromPassword(allocator: NeverFailingAllocator, accountCode: AccountCode, password: []const u8, shouldProtect: bool) error{syserr}!PasswordEncodedAccountCode {
		var salt: [32]u8 = undefined;
		main.io.random(&salt);
		const saltBase64 = allocator.alloc(u8, std.base64.standard.Encoder.calcSize(salt.len));
		std.debug.assert(std.base64.standard.Encoder.encode(saltBase64, &salt).len == saltBase64.len);

		var key: [32]u8 = undefined;
		defer std.crypto.secureZero(u8, &key);
		keyFromPassword(.argon2_aes_gcm, saltBase64, password, &key);

		const encryptedBuffer = allocator.alloc(u8, accountCode.text.len);
		var authenticationTag: [std.crypto.aead.aes_gcm.Aes256Gcm.tag_length]u8 = undefined;
		var nonce: [std.crypto.aead.aes_gcm.Aes256Gcm.nonce_length]u8 = undefined;
		main.io.random(&nonce);
		std.crypto.aead.aes_gcm.Aes256Gcm.encrypt(encryptedBuffer, &authenticationTag, accountCode.text, &.{}, nonce, key);

		const protected = shouldProtect and protection.canProtect();
		var data: []u8 = undefined;
		if (protected) {
			data = protection.protect(allocator, encryptedBuffer) catch |err| {
				if (err == error.syserr) return error.syserr else unreachable;
			};
			defer allocator.free(encryptedBuffer); // Deferred, because that way even if a syserr is thrown it will still get freed
		} else {
			data = encryptedBuffer;
		}
		return .{
			.typ = .argon2_aes_gcm,
			.protected = protected,
			.salt = saltBase64,
			.data = data,
			.nonce = allocator.dupe(u8, &nonce),
			.authenticationTag = allocator.dupe(u8, &authenticationTag),
		};
	}

	pub fn initUnencoded(allocator: NeverFailingAllocator, accountCode: AccountCode, shouldProtect: bool) error{syserr}!PasswordEncodedAccountCode {
		const protected = shouldProtect and protection.canProtect();
		var data: []u8 = undefined;
		if (protected) {
			data = protection.protect(allocator, accountCode.text) catch |err| {
				if (err == error.syserr) return error.syserr else unreachable;
			};
		} else {
			data = allocator.dupe(u8, accountCode.text);
		}
		return .{
			.typ = .none,
			.protected = protected,
			.salt = &.{},
			.nonce = &.{},
			.data = data,
			.authenticationTag = &.{},
		};
	}

	pub fn deinit(self: PasswordEncodedAccountCode, allocator: NeverFailingAllocator) void {
		allocator.free(self.salt);
		allocator.free(self.data);
		allocator.free(self.nonce);
		allocator.free(self.authenticationTag);
	}

	pub fn decryptFromPassword(self: PasswordEncodedAccountCode, password: []const u8, failureText: *main.ListManaged(u8)) !AccountCode {
		if (self.protected and !protection.canProtect()) return error.Invalid;
		if (self.typ == .none) {
			var data = self.data;
			if (self.protected) {
				data = try protection.unprotect(main.stackAllocator, data);
			}
			defer if (self.protected) {
				std.crypto.secureZero(u8, data);
				main.stackAllocator.free(data);
			};
			return AccountCode.initFromUserInput(data, failureText);
		}
		var key: [32]u8 = undefined;
		defer std.crypto.secureZero(u8, &key);
		keyFromPassword(self.typ, self.salt, password, &key);

		switch (self.typ) {
			.none => unreachable,
			.argon2_aes_gcm => {
				var data = self.data;
				if (self.protected) {
					data = try protection.unprotect(main.stackAllocator, data);
				}
				defer if (self.protected) {
					std.crypto.secureZero(u8, data);
					main.stackAllocator.free(data);
				};

				if (self.authenticationTag.len != std.crypto.aead.aes_gcm.Aes256Gcm.tag_length) return error.Invalid;
				if (self.nonce.len != std.crypto.aead.aes_gcm.Aes256Gcm.nonce_length) return error.Invalid;
				const authenticationTag = self.authenticationTag[0..std.crypto.aead.aes_gcm.Aes256Gcm.tag_length];
				const nonce = self.nonce[0..std.crypto.aead.aes_gcm.Aes256Gcm.nonce_length];
				const decryptedBuffer = main.stackAllocator.alloc(u8, data.len);
				defer main.stackAllocator.free(decryptedBuffer);
				defer std.crypto.secureZero(u8, decryptedBuffer);
				try std.crypto.aead.aes_gcm.Aes256Gcm.decrypt(decryptedBuffer, data, authenticationTag.*, &.{}, nonce.*, key);
				return AccountCode.initFromUserInput(decryptedBuffer, failureText);
			},
		}
	}

	fn keyFromPassword(typ: EncodingType, salt: []const u8, password: []const u8, key: *[32]u8) void {
		switch (typ) {
			.none => unreachable,
			.argon2_aes_gcm => {
				std.crypto.pwhash.argon2.kdf(main.globalAllocator.allocator, key, password, salt, .{
					.t = 10,
					.m = 32000,
					.p = 1,
				}, .argon2id, main.io) catch unreachable;
			},
		}
	}

	pub fn fromZon(allocator: NeverFailingAllocator, zon: ZonElement) !PasswordEncodedAccountCode {
		if (zon == .null) return .empty;
		var self: PasswordEncodedAccountCode = undefined;

		self.typ = std.meta.stringToEnum(EncodingType, zon.get([]const u8, "type") orelse return error.Invalid) orelse return error.Invalid;
		self.protected = zon.get(bool, "protected") orelse false;
		self.salt = allocator.dupe(u8, zon.get([]const u8, "salt") orelse "");
		errdefer allocator.free(self.salt);
		if (self.salt.len < 32 and self.typ != .none) return error.Invalid;

		const base64EncodedData = zon.get([]const u8, "data") orelse "";
		self.data = allocator.alloc(u8, try std.base64.standard.Decoder.calcSizeForSlice(base64EncodedData));
		errdefer allocator.free(self.data);
		try std.base64.standard.Decoder.decode(self.data, base64EncodedData);
		if (self.data.len == 0 and self.typ != .none) return error.Invalid;

		const base64EncodedTag = zon.get([]const u8, "authenticationTag") orelse "";
		self.authenticationTag = allocator.alloc(u8, try std.base64.standard.Decoder.calcSizeForSlice(base64EncodedTag));
		errdefer allocator.free(self.authenticationTag);
		try std.base64.standard.Decoder.decode(self.authenticationTag, base64EncodedTag);
		if (self.authenticationTag.len == 0 and self.typ != .none) return error.Invalid;

		const base64EncodedNonce = zon.get([]const u8, "nonce") orelse "";
		self.nonce = allocator.alloc(u8, try std.base64.standard.Decoder.calcSizeForSlice(base64EncodedNonce));
		errdefer allocator.free(self.nonce);
		try std.base64.standard.Decoder.decode(self.nonce, base64EncodedNonce);
		if (self.nonce.len == 0 and self.typ != .none) return error.Invalid;

		return self;
	}

	pub fn toZon(self: PasswordEncodedAccountCode, allocator: NeverFailingAllocator) ZonElement {
		const zon = ZonElement.initObject(allocator);
		zon.put("type", @tagName(self.typ));
		zon.put("protected", self.protected);
		zon.putOwnedString("salt", self.salt);

		const base64EncodedData = main.stackAllocator.alloc(u8, std.base64.standard.Encoder.calcSize(self.data.len));
		defer main.stackAllocator.free(base64EncodedData);
		zon.putOwnedString("data", std.base64.standard.Encoder.encode(base64EncodedData, self.data));

		const base64EncodedTag = main.stackAllocator.alloc(u8, std.base64.standard.Encoder.calcSize(self.authenticationTag.len));
		defer main.stackAllocator.free(base64EncodedTag);
		zon.putOwnedString("authenticationTag", std.base64.standard.Encoder.encode(base64EncodedTag, self.authenticationTag));

		const base64EncodedNonce = main.stackAllocator.alloc(u8, std.base64.standard.Encoder.calcSize(self.nonce.len));
		defer main.stackAllocator.free(base64EncodedNonce);
		zon.putOwnedString("nonce", std.base64.standard.Encoder.encode(base64EncodedNonce, self.nonce));

		return zon;
	}
};
